In [2]:
import sys
sys.path.insert(0, '../src/network_analysis/lib') 
from containers import GraphAPI
from analytics import DataPool, Report
from characterization import Distances, Connectivity, ClusteringAndCycles, Centrality

In [4]:
datapool = DataPool()
datapool.load('../data/info', n=True, m=True, r=True)

../data/info/flags.dat loaded in memory
../data/info/networks.dat loaded in memory
../data/info/measures.dat loaded in memory
../data/info/results.dat loaded in memory

In [7]:
datapool.networks

,collection,dataset,label,N,M,K,abbr,graph,source
network_id,,,,,,,,,
0,robustness,toy,BA,100,197,NaN,"BA({'n': 100, 'm': 2})_854227349",<containers.GraphAPI object at 0x7f2293103af0>,network_000000.txt
1,robustness,toy,BA,100,197,NaN,"BA({'n': 100, 'm': 2})_1078249842",<containers.GraphAPI object at 0x7f2293103880>,network_000001.txt
2,robustness,toy,BA,100,197,NaN,"BA({'n': 100, 'm': 2})_696283757",<containers.GraphAPI object at 0x7f2293103460>,network_000002.txt
3,robustness,toy,BA,100,197,NaN,"BA({'n': 100, 'm': 2})_1988659721",<containers.GraphAPI object at 0x7f2293103820>,network_000003.txt
4,robustness,toy,BA,100,197,NaN,"BA({'n': 100, 'm': 2})_477523455",<containers.GraphAPI object at 0x7f2293103580>,network_000004.txt
...,...,...,...,...,...,...,...,...,...
145,robustness,toy,BA,100,390,NaN,"BA({'n': 100, 'm': 4})_340565057",<containers.GraphAPI object at 0x7f2292dd52e0>,network_000145.txt
146,robustness,toy,BA,100,390,NaN,"BA({'n': 100, 'm': 4})_936831151",<containers.GraphAPI object at 0x7f2292dd5370>,network_000146.txt
147,robustness,toy,BA,100,390,NaN,"BA({'n': 100, 'm': 4})_1824413104",<containers.GraphAPI object at 0x7f2292dd5400>,network_000147.txt
148,robustness,toy,BA,100,390,NaN,"BA({'n': 100, 'm': 4})_1721083612",<containers.GraphAPI object at 0x7f2292dd5490>,network_000148.txt
149,robustness,toy,BA,100,390,NaN,"BA({'n': 100, 'm': 4})_1747344017",<containers.GraphAPI object at 0x7f2292dd5520>,network_000149.txt

In [8]:
datapool.measures

,name,varname,symbol,scope,category,function,dependence,default
measure_id,,,,,,,,
0,shortest distances,min_dist,d_ij,vertex pair,distances,<bound method Distances.shortest_dist of <clas...,None,None
1,shortest distances distribution,p_min_dist,P(d_ij),distrib,distances,<bound method Distances.shortest_dist_distrib ...,[shortest distances],None
2,diameter,diam,D,graph,distances,<bound method Distances.diameter of <class 'ch...,[shortest distances distribution],None
3,average geodesic distance,avg_gdist,l,graph,distances,<bound method Distances.avg_geodesic_dist of <...,[shortest distances distribution],None
4,global efficiency,effic,E,graph,distances,<bound method Distances.global_efficiency of <...,[shortest distances distribution],None
5,harmonic mean of the geodesic distances,hmean_gdist,h,graph,distances,<bound method Distances.hmean_geodesic_dist of...,[global efficiency],None
6,vertex degree,deg,k_i,vertex,connectivity,<bound method Connectivity.vertex_degree of <c...,None,None
7,maximum degree,max_deg,k_max,graph,connectivity,<bound method Connectivity.max_degree of <clas...,[vertex degree],None
8,degree distribution,p_deg,P(k),distrib,connectivity,<bound method Connectivity.deg_distrib of <cla...,[vertex degree],None
9,remaining degree distribution,q_deg,q(k),distrib,connectivity,<bound method Connectivity.rem_deg_distrib of ...,[degree distribution],None
10,average degree,avg_deg,Avg[k],graph,connectivity,<bound method Connectivity.avg_degree of <clas...,[degree distribution],None
11,degree's variance,var_deg,Var[k],graph,connectivity,<bound method Connectivity.var_degree of <clas...,"[degree distribution, average degree]",None
12,degree's skewness,skw_deg,Skew[k],graph,connectivity,<bound method Connectivity.skw_degree of <clas...,"[degree distribution, average degree, degree's...",None
13,degree's kurtosis,krt_deg,Kurt[k],graph,connectivity,<bound method Connectivity.krt_degree of <clas...,"[degree distribution, average degree, degree's...",None
14,qt. of triplets,qt_tri,N3(i),vertex,clustering and cycles,<bound method ClusteringAndCycles.qt_triplets ...,[vertex degree],None
15,vertex clustering coefficient,cc,C_i,vertex,clustering and cycles,<bound method ClusteringAndCycles.vertex_clust...,[qt. of triplets],None
16,network clustering coefficient,avg_cc,C,graph,clustering and cycles,<bound method ClusteringAndCycles.network_clus...,[vertex clustering coefficient],None
17,betweenness centrality,bc,B_i,vertex,centrality,<bound method Centrality.betweenness_centralit...,None,None
18,average betweenness centrality,avg_bc,<B>,graph,centrality,<bound method Centrality.avg_betweenness_centr...,[betweenness centrality],None
19,central point domimnance,cpd,CPD,graph,centrality,<bound method Centrality.central_point_dominan...,[betweenness centrality],None

In [9]:
m_mask = (datapool.measures['scope']=='graph')
rep_g = Report.make(datapool, measure_subset=m_mask, header='varname', expand=True, detail=False)
rep_g

measures                                  diam avg_gdist     effic  \
dataset abbr
toy     BA({'n': 100, 'm': 2})_1052861942    6    3.1324  0.353647
        BA({'n': 100, 'm': 2})_1078249842    6    3.1346  0.353217
        BA({'n': 100, 'm': 2})_1119879636    5     2.989   0.36658
        BA({'n': 100, 'm': 2})_1138326505    6    3.0194  0.364713
        BA({'n': 100, 'm': 2})_1144257784    6    3.0168  0.363597
...                                        ...       ...       ...
        BA({'n': 100, 'm': 4})_949213581     4    2.3656  0.457683
        BA({'n': 100, 'm': 4})_970144785     4     2.324    0.4642
        BA({'n': 100, 'm': 4})_973800965     4    2.3312  0.462967
        BA({'n': 100, 'm': 4})_990539191     4     2.334    0.4624
        BA({'n': 100, 'm': 4})_999466877     4    2.3262     0.464

measures                                  hmean_gdist max_deg avg_deg  \
dataset abbr
toy     BA({'n': 100, 'm': 2})_1052861942    2.827681      24    3.94
        BA({'n': 100, 'm': 2})_1078249842    2.831123      18    3.94
        BA({'n': 100, 'm': 2})_1119879636    2.727918      29    3.94
        BA({'n': 100, 'm': 2})_1138326505    2.741879      23    3.94
        BA({'n': 100, 'm': 2})_1144257784      2.7503      24    3.94
...                                               ...     ...     ...
        BA({'n': 100, 'm': 4})_949213581     2.184917      25     7.8
        BA({'n': 100, 'm': 4})_970144785     2.154244      38     7.8
        BA({'n': 100, 'm': 4})_973800965     2.159983      32     7.8
        BA({'n': 100, 'm': 4})_990539191      2.16263      36     7.8
        BA({'n': 100, 'm': 4})_999466877     2.155172      41     7.8

measures                                   var_deg     skw_deg      krt_deg  \
dataset abbr
toy     BA({'n': 100, 'm': 2})_1052861942  10.7564  120.976368  2043.441977
        BA({'n': 100, 'm': 2})_1078249842  10.1164   90.321168  1134.138553
        BA({'n': 100, 'm': 2})_1119879636  13.7364  202.452768  4480.911945
        BA({'n': 100, 'm': 2})_1138326505  14.2964  169.373568  2729.320841
        BA({'n': 100, 'm': 2})_1144257784  12.2164  147.639168  2566.069513
...                                            ...         ...          ...
        BA({'n': 100, 'm': 4})_949213581      28.9     272.688    4386.7528
        BA({'n': 100, 'm': 4})_970144785     35.56     558.624   13616.3632
        BA({'n': 100, 'm': 4})_973800965     34.12      471.12    9912.1456
        BA({'n': 100, 'm': 4})_990539191     32.58     446.916     9840.492
        BA({'n': 100, 'm': 4})_999466877     37.36     655.044   17613.9472

measures                                     avg_cc  avg_bc          cpd
dataset abbr
toy     BA({'n': 100, 'm': 2})_1052861942  0.197522  107.12  1403.679773
        BA({'n': 100, 'm': 2})_1078249842  0.168431  107.23   999.055508
        BA({'n': 100, 'm': 2})_1119879636  0.286997   99.95  1932.066624
        BA({'n': 100, 'm': 2})_1138326505  0.282533  101.47  1257.252202
        BA({'n': 100, 'm': 2})_1144257784  0.212645  101.34  1380.688937
...                                             ...     ...          ...
        BA({'n': 100, 'm': 4})_949213581    0.28865   68.78   424.163711
        BA({'n': 100, 'm': 4})_970144785   0.379938    66.7   961.840626
        BA({'n': 100, 'm': 4})_973800965   0.421543   67.06   650.710755
        BA({'n': 100, 'm': 4})_990539191   0.360195    67.2   814.473419
        BA({'n': 100, 'm': 4})_999466877   0.392956   66.81   955.236713

[150 rows x 12 columns]

In [10]:
m_mask = (datapool.measures['scope']=='vertex')
rep_v = Report.make(datapool, measure_subset=m_mask, header='varname', expand=True, detail=False)
rep_v

measures                                         deg qt_tri        cc  \
dataset abbr                              vertex
toy     BA({'n': 100, 'm': 2})_1052861942 0        3    3.0  0.666667
                                          1       16  120.0  0.166667
                                          2       24  276.0  0.115942
                                          3       11   55.0  0.109091
                                          4        5   10.0       0.4
...                                               ..    ...       ...
        BA({'n': 100, 'm': 4})_999466877  95       4    6.0       0.0
                                          96       4    6.0  1.333333
                                          97       4    6.0       0.0
                                          98       4    6.0  0.666667
                                          99       4    6.0  0.333333

measures                                                   bc
dataset abbr                              vertex
toy     BA({'n': 100, 'm': 2})_1052861942 0         63.439795
                                          1        976.646117
                                          2       1496.762975
                                          3        589.075983
                                          4        112.436888
...                                                       ...
        BA({'n': 100, 'm': 4})_999466877  95         9.661143
                                          96         3.939123
                                          97        14.153986
                                          98         2.359858
                                          99          8.26829

[15000 rows x 4 columns]